version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    restart: always
    tty: true
    container_name: nginx
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.confs
      - ./:/var/www/html